idk, too damn late

diff --git a/utils/compile-and-link b/utils/compile-and-link
--- a/utils/compile-and-link
+++ b/utils/compile-and-link
@@ -3,18 +3,18 @@
 set filename $argv[1]
 set filenameNoExtention (echo -n $filename | cut -d"." -f1)
 
-echo "compiling $filename in elf64 format..."
+echo "compiling $filename in elf32 format..."
 
-if nasm -f elf64 $filename -o $filenameNoExtention.o
-    if ld $filenameNoExtention.o -o $filenameNoExtention.elf64
+if nasm -f elf32 $filename -o $filenameNoExtention.o
+    if ld $filenameNoExtention.o -o $filenameNoExtention.elf32
         if rm $filenameNoExtention.o
             echo -n "done!"
         else
             echo "FAIL! : rm $filenameNoExtention.o" 1>&2
         end
     else
-        echo "FAIL! : ld $filenameNoExtention.o -o $filenameNoExtention.elf64" 1>&2
+        echo "FAIL! : ld $filenameNoExtention.o -o $filenameNoExtention.elf32" 1>&2
     end
 else 
-    echo  "FAIL! : nasm -f elf64 $filename -o $filenameNoExtention.o" 1>&2
+    echo  "FAIL! : nasm -f elf32 $filename -o $filenameNoExtention.o" 1>&2
 end
